'use strict';
const KEY='dsssb-image-test-v2', root=document.getElementById('app'), timer=document.getElementById('timer');
let state=null, reviewIndex=0,renderTicket=0;
const questionMap=new Map(BANK.map(q=>[q.id,q]));
try{state=JSON.parse(localStorage.getItem(KEY));if(state?.version!==2)state=null;}catch{}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=ms=>{const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;};
const elapsed=()=>state?Math.max(0,(state.finishedAt||Date.now())-state.startedAt):0;
const sectionTime=i=>state.sections[i].spent+(state.active===i&&!state.finishedAt?Math.max(0,Date.now()-state.sections[i].startedAt):0);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{document.getElementById('save-note')?.replaceChildren('Storage unavailable: keep this tab open.');}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function newTest(){
 if(state&&!state.finishedAt&&!confirm('Discard this unfinished test and begin again?'))return;
 const penalty=Number(document.getElementById('penalty')?.value||0);
 const selection=document.getElementById('test-mode')?.value||'random';
 const chosen=selection==='random'?null:MOCKS.find(m=>m.id===selection);
 function pick(i){
  const qs=BANK.filter(q=>q.section===i&&q.verified&&(!chosen||q.mock===chosen.number));
  const groups=new Map();for(const q of qs){const k=q.group||q.id;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(q.id);}
  if(chosen)return [...groups.values()].flat();
  const result=[];for(const unit of shuffle([...groups.values()])){if(result.length+unit.length<=20)result.push(...unit);if(result.length===20)break;}
  if(result.length!==20)throw new Error('Not enough checked questions in '+SECTIONS[i]);return result;
 }
 const secs=SECTIONS.map((name,i)=>({name,ids:pick(i),done:false,spent:0,startedAt:null,answers:{}}));
 state={version:2,startedAt:Date.now(),finishedAt:null,active:null,index:0,penalty,title:chosen?chosen.title:"Random mixed test",sections:secs};save();render();window.scrollTo(0,0);
}
function startSection(i){if(!state||state.finishedAt||state.active!==null||state.sections[i].done)return;state.active=i;state.index=0;state.sections[i].startedAt=Date.now();save();render();window.scrollTo(0,0);}
function answer(a){if(state?.active===null||state?.finishedAt)return;const s=state.sections[state.active];if(s.done)return;const id=s.ids[state.index];if(a)s.answers[id]=a;else delete s.answers[id];save();render();}
function go(i){if(state?.active===null||state?.finishedAt)return;const s=state.sections[state.active];state.index=Math.max(0,Math.min(s.ids.length-1,i));save();render();window.scrollTo(0,0);}
function submitSection(){if(state?.active===null||state?.finishedAt)return;const s=state.sections[state.active];const blank=s.ids.length-Object.keys(s.answers).length;
 if(!confirm(`Submit ${s.name}? ${blank} unanswered. You cannot return to this section.`))return;
 s.spent=sectionTime(state.active);s.startedAt=null;s.done=true;state.active=null;
 if(state.sections.every(s=>s.done))state.finishedAt=Date.now();save();render();window.scrollTo(0,0);
}
function imageHtml(q){return (q.passage?`<details class="passage" open><summary>Comprehension passage</summary>${q.passage.map(p=>`<img src="${ASSETS[p]||p}" alt="Original comprehension passage">`).join('')}</details>`:'')+q.images.map((p,i)=>`<img src="${ASSETS[p]||p}" alt="Original question ${q.number}, part ${i+1}">`).join('');}
function summary(){return state.sections.map((s,i)=>{let correct=0,wrong=0;for(const id of s.ids){const q=questionMap.get(id),a=s.answers[id];if(a===q.answer)correct++;else if(a)wrong++;}return {name:s.name,correct,wrong,blank:s.ids.length-correct-wrong,score:correct-wrong*state.penalty,ms:sectionTime(i),count:s.ids.length};});}
function showReview(i){reviewIndex=Math.max(0,Math.min(state.sections.reduce((n,s)=>n+s.ids.length,0)-1,i));render('review');window.scrollTo(0,0);}
function render(mode){
 const ticket=++renderTicket;
 if(!state){root.innerHTML=`<h1>Image mock test</h1><p>100 questions · 5 sections · 60 minutes</p><div class="stats">${SECTIONS.slice(0,3).map((name,i)=>`<div class="stat"><strong>${BANK.filter(q=>q.section===i).length}</strong>${escape(name)}</div>`).join('')}<div class="stat"><strong>${BANK.length}</strong>Total checked questions</div></div><div class="card"><h2>Begin your test</h2><p>Questions appear exactly as printed. Select A, B, C or D beneath the image.</p><label for="test-mode">Choose your test</label><select id="test-mode"><option value="random">Random mixed test — 20 questions per section</option>${MOCKS.map(m=>`<option value="${m.id}" ${m.complete?'':'disabled'}>${escape(m.title)}${m.complete?'':' — incomplete, excluded'}</option>`).join('')}</select><p class="muted">Random tests draw from checked questions across all source books. Shared passages stay with their question groups. Original mock tests retain their printed question order.</p><div class="notice">${BANK.length} questions included from ${MANIFEST.sourceCount} source PDFs. ${MANIFEST.excluded} questions awaiting review are excluded from scored tests. Correct answers follow the supplied books; source mistakes may remain.</div><label for="penalty">Marks deducted for a wrong answer</label><select id="penalty"><option value="0">0 — no negative marking</option><option value="0.25">0.25</option></select><p>Correct: +1 · Unanswered: 0</p><button class="primary" id="begin">Start 60-minute test</button></div><div class="card"><h2>Test rules</h2><p>Choose your section order. Once a section starts, finish it before selecting another. Submitted sections stay locked. After 60 minutes, the red timer counts extra time and the test continues.</p><p>The test clock includes breaks and time between sections. Section timing includes time away while that section is open.</p></div>`;document.getElementById('begin').onclick=newTest;tick();return;}
 if(state.finishedAt){const sums=summary(),total=sums.reduce((a,s)=>a+s.score,0),max=Math.max(...sums.map(s=>s.ms)),slow=sums.filter(s=>s.ms===max).map(s=>s.name).join(', '),all=state.sections.flatMap(s=>s.ids.map(id=>({q:questionMap.get(id),a:s.answers[id]})));
 if(mode==='review'){const x=all[reviewIndex];if(!ASSETS[x.q.images[0]]){root.innerHTML='<div class="card">Loading question image…</div>';prepareImages(x.q).then(()=>{if(ticket===renderTicket)render("review");}).catch(e=>{root.innerHTML='<div class="notice">'+escape(e.message)+'</div>';});return;}root.innerHTML=`<div class="review-nav"><button id="results">Results</button><button id="prev">Previous</button><button id="next">Next</button><span class="pill">${reviewIndex+1} / ${all.length}</span></div><div class="card review"><h2>${escape(SECTIONS[x.q.section])} · Question ${reviewIndex%20+1}</h2><p class="${x.a===x.q.answer?'good':'bad'}">Your answer: <b>${x.a||'Unanswered'}</b> · Correct answer: <b>${x.q.answer}</b></p>${imageHtml(x.q)}<p class="muted">${escape(x.q.source)} · Source question ${x.q.number} · PDF page ${x.q.sourcePages.join(', ')}</p></div>`;document.getElementById('results').onclick=()=>render();document.getElementById('prev').onclick=()=>showReview(reviewIndex-1);document.getElementById('next').onclick=()=>showReview(reviewIndex+1);tick();return;}
 root.innerHTML=`<h1>Test results</h1><p class="muted">${escape(state.title)}</p><div class="stats"><div class="stat"><strong>${total.toFixed(2)}</strong>Score / 100</div><div class="stat"><strong>${sums.reduce((a,s)=>a+s.correct,0)}</strong>Correct</div><div class="stat"><strong>${fmt(elapsed())}</strong>Total time</div><div class="stat"><strong>${fmt(Math.max(0,elapsed()-3600000))}</strong>Extra time</div></div><div class="card"><h2>Section analysis</h2><p>Most time spent: <b>${escape(slow)}</b>. Compare time and accuracy to choose what to practise.</p><div class="table-wrap"><table><thead><tr><th>Section</th><th>Correct</th><th>Wrong</th><th>Blank</th><th>Score</th><th>Time</th><th>Time / question</th></tr></thead><tbody>${sums.map(s=>`<tr><td>${escape(s.name)}<div class="bar"><div style="width:${max?s.ms/max*100:0}%"></div></div></td><td>${s.correct}</td><td>${s.wrong}</td><td>${s.blank}</td><td>${s.score.toFixed(2)}</td><td>${fmt(s.ms)}</td><td>${fmt(s.ms/s.count)}</td></tr>`).join('')}</tbody></table></div><p class="muted">Time between sections: ${fmt(Math.max(0,elapsed()-sums.reduce((a,s)=>a+s.ms,0)))}. Section times measure elapsed time, including breaks while a section is open.</p></div><div class="actions"><button class="primary" id="export">Download test PDF with answers</button><button id="review">Review question images</button><button id="restart">New test</button></div><p id="export-status" role="status"></p>`;
 document.getElementById('export').onclick=async()=>{const b=document.getElementById('export');b.disabled=true;document.getElementById('export-status').textContent='Preparing PDF…';try{await exportTestPdf(state,all,sums);document.getElementById('export-status').textContent='PDF downloaded.';}catch(e){document.getElementById('export-status').textContent='PDF export failed. Please try again. '+e.message;}finally{b.disabled=false;}};document.getElementById('review').onclick=()=>showReview(0);document.getElementById('restart').onclick=()=>{state=null;localStorage.removeItem(KEY);render();};tick();return;
 }
 if(state.active===null){root.innerHTML=`<h1>Choose your next section</h1><p>The test timer is running. Each section has 20 questions.</p><div class="sections">${state.sections.map((s,i)=>`<div class="card section ${s.done?'locked':''}"><span class="pill">${s.done?'Submitted · locked':'Not started'}</span><h2>${escape(s.name)}</h2><p class="muted">${s.done?'Time: '+fmt(s.spent):'20 questions · 20 marks'}</p><button data-start="${i}" class="primary" ${s.done?'disabled':''}>${s.done?'Locked':'Start section'}</button></div>`).join('')}</div><p id="save-note" class="muted">Progress saved on this device. Reopening resumes the same timer.</p>`;root.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startSection(Number(b.dataset.start)));tick();return;}
 const s=state.sections[state.active],q=questionMap.get(s.ids[state.index]);if(!ASSETS[q.images[0]]){root.innerHTML=`<h1>${escape(s.name)}</h1><div class="card"><p>Loading question image…</p><p class="muted">The timer continues while loading.</p></div>`;prepareImages(q).then(()=>{if(ticket===renderTicket)render();}).catch(e=>{root.innerHTML='<div class="notice">'+escape(e.message)+'</div>';});tick();return;}root.innerHTML=`<h1>${escape(s.name)}</h1><p class="muted">Section locked while in progress · Question ${state.index+1} / ${s.ids.length}</p><div class="workspace"><div class="card question">${imageHtml(q)}<div class="options" role="group" aria-label="Choose your answer">${['A','B','C','D'].map(a=>`<button data-answer="${a}" class="${s.answers[q.id]===a?'selected':''}" aria-pressed="${s.answers[q.id]===a}">${a}</button>`).join('')}</div><div class="actions"><button id="previous" ${state.index===0?'disabled':''}>Previous</button><button id="clear">Clear answer</button><button id="nextq" ${state.index===s.ids.length-1?'disabled':''}>Next</button></div><p class="muted">${escape(q.source)} · Source question ${q.number}</p></div><aside class="sidebar"><div class="card"><h2>Questions</h2><p>${Object.keys(s.answers).length} / ${s.ids.length} answered</p><div class="palette">${s.ids.map((id,i)=>`<button data-go="${i}" class="${s.answers[id]?'answered':''} ${i===state.index?'current':''}" aria-label="Question ${i+1}${s.answers[id]?', answered':''}">${i+1}</button>`).join('')}</div><p>Section time: <b id="section-timer">${fmt(sectionTime(state.active))}</b></p><button class="danger" id="submit">Submit section</button><p class="muted">Submission is final. You cannot return to this section.</p><p id="save-note" class="muted">Progress saved on this device.</p></div></aside></div>`;
 root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(Number(b.dataset.go)));document.getElementById('previous').onclick=()=>go(state.index-1);document.getElementById('nextq').onclick=()=>go(state.index+1);document.getElementById('clear').onclick=()=>answer(null);document.getElementById('submit').onclick=submitSection;const next=questionMap.get(s.ids[state.index+1]);if(next)prepareImages(next).catch(()=>{});tick();
}
function tick(){const t=elapsed(),over=t>=3600000;timer.classList.toggle('overtime',!!state&&over);timer.textContent=state?(over?`+${fmt(t-3600000)}`:fmt(3600000-t)):'60:00';timer.setAttribute('aria-label',over?'Extra time '+fmt(t-3600000):'Time remaining '+fmt(3600000-t));if(state?.active!==null&&state&&!state.finishedAt){const el=document.getElementById('section-timer');if(el)el.textContent=fmt(sectionTime(state.active));}}
setInterval(tick,250);window.addEventListener('pagehide',save);render();
